init:
	cp compose.override.yml.sample conpose.override.yml

pjt:
	cargo new --bin template_rust

run:
	cargo run -- ./src/cmd

build:
	cargo build

test:
	cargo test

fmt:
	cargo fmt


.PHONY: init create run build test, fmt