// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package table

import (
	"database/sql"
)

type Author struct {
	ID   int64          `db:"id" json:"id"`
	Name string         `db:"name" json:"name"`
	Bio  sql.NullString `db:"bio" json:"bio"`
}
