version: "3"
services:
  gopher:
    image: golang:1.20
    working_dir: /go/src
    volumes:
      - ./src:/go/src
      - ./bin:/go/bin
      - ./csv:/go/csv
      - ./sqlc:/go/sqlc
      - ./migration:/go/migration
    networks:
      - aic-network
    command: go get github.com/kyleconroy/sqlc/cmd/sqlc@latest && sqlc generate

  db:
    container_name: aic-db
    image: mysql:latest
    volumes:
      - ./volume:/docker-entrypoint-initdb.d
    networks:
      - aic-network

  redis:
    container_name: aic-redis
    image: redis:latest
    networks:
      - aic-network

  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - aic-network

  sendgrid:
    container_name: sendgrid
    image: ykanazawa/sendgrid-maildev
    hostname: sendgrid-maildev
    environment:
      - SENDGRID_DEV_API_SERVER=:3030
      - SENDGRID_DEV_API_KEY=test_api_key
      - SENDGRID_DEV_SMTP_SERVER=127.0.0.1:1025
    ports:
      - 1025:1025 #sendGrid → maildevへの中継
      - 1080:1080 #maildevのブラウザ確認用ポート
      - 3030:3030 #SendGridのAPIエンドポイントのポート
    networks:
      - aic-network

networks:
  aic-network:
    driver: bridge
